spring.application.name=RestApi's

spring.datasource.url=jdbc:postgresql://localhost:5432/Notes
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
